Neko.

diff --git a/unikernels/unikraft-cu/Dockerfile b/unikernels/unikraft-cu/Dockerfile
--- a/unikernels/unikraft-cu/Dockerfile
+++ b/unikernels/unikraft-cu/Dockerfile
@@ -1,3 +1,6 @@
+FROM ghcr.io/m1k1o/neko/chromium:latest AS neko
+FROM kernel-xorg-deps AS xorg-deps
+
 FROM docker.io/ubuntu:22.04
 
 ENV DEBIAN_FRONTEND=noninteractive
@@ -55,6 +58,47 @@ RUN apt-get update && \
     unzip && \
     apt-get clean
 
+# runtime
+ENV USERNAME=kernel
+RUN set -eux; \
+    apt-get update; \
+    apt-get install -y --no-install-recommends \
+        wget ca-certificates python2 supervisor \
+        pulseaudio dbus-x11 xserver-xorg-video-dummy \
+        libcairo2 libxcb1 libxrandr2 libxv1 libopus0 libvpx7 \
+        gstreamer1.0-plugins-base gstreamer1.0-plugins-good \
+        gstreamer1.0-plugins-bad gstreamer1.0-plugins-ugly \
+        gstreamer1.0-pulseaudio gstreamer1.0-omx; \
+    #
+    # install libxcvt0 (not available in debian:bullseye)
+    ARCH=$(dpkg --print-architecture); \
+    wget http://ftp.de.debian.org/debian/pool/main/libx/libxcvt/libxcvt0_0.1.2-1_${ARCH}.deb; \
+    apt-get install --no-install-recommends ./libxcvt0_0.1.2-1_${ARCH}.deb; \
+    rm ./libxcvt0_0.1.2-1_${ARCH}.deb; \
+    #
+    # create a non-root user
+    useradd $USERNAME; \
+    adduser $USERNAME audio; \
+    adduser $USERNAME video; \
+    adduser $USERNAME pulse; \
+    #
+    # workaround for an X11 problem: http://blog.tigerteufel.de/?p=476
+    mkdir /tmp/.X11-unix; \
+    chmod 1777 /tmp/.X11-unix; \
+    chown $USERNAME /tmp/.X11-unix/; \
+    #
+    # make directories for neko
+    mkdir -p /etc/neko /var/www /var/log/neko \
+        /tmp/runtime-$USERNAME \
+        /home/$USERNAME/.config/pulse  \
+        /home/$USERNAME/.local/share/xorg; \
+    chmod 1777 /var/log/neko; \
+    chown $USERNAME /var/log/neko/ /tmp/runtime-$USERNAME; \
+    chown -R $USERNAME:$USERNAME /home/$USERNAME; \
+    # clean up
+    apt-get clean -y; \
+    rm -rf /var/lib/apt/lists/* /var/cache/apt/
+
 # install chromium & ncat for proxying the remote debugging port
 RUN add-apt-repository -y ppa:xtradeb/apps
 RUN apt update -y && apt install -y chromium ncat
@@ -69,8 +113,19 @@ ENV DISPLAY_NUM=1
 ENV HEIGHT=768
 ENV WIDTH=1024
 
-COPY image-chromium/ /
-COPY ./wrapper.sh /wrapper.sh
+USER kernel
+WORKDIR /home/kernel
 
-ENTRYPOINT [ "/wrapper.sh" ]
+COPY xorg.conf /etc/neko/xorg.conf
+COPY neko.yaml /etc/neko/neko.yaml
+COPY --from=neko /usr/bin/neko /usr/bin/neko
+COPY --from=neko /var/www /var/www
+COPY --from=xorg-deps /usr/local/lib/xorg/modules/drivers/dummy_drv.so /usr/lib/xorg/modules/drivers/dummy_drv.so
+COPY --from=xorg-deps /usr/local/lib/xorg/modules/input/neko_drv.so /usr/lib/xorg/modules/input/neko_drv.so
+LABEL net.m1k1o.neko.api-version=3
+
+COPY image-chromium/ /home/kernel
+COPY ./wrapper.sh /home/kernel/wrapper.sh
+
+ENTRYPOINT [ "/home/kernel/wrapper.sh" ]
 
